language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install python-coveralls
  - pip install coverage
  - pip install nose           # Add me to install nose
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage # Add me to run nose with coverage support.
after_success:
  - coveralls
